"""RSGP constants."""

DAYS_IN_YEAR = 365
HOURS_IN_DAY = 24
HOURS_IN_YEAR = HOURS_IN_DAY * DAYS_IN_YEAR
MINUTES_IN_HOUR = 60
MINUTES_IN_DAY = MINUTES_IN_HOUR * HOURS_IN_DAY
MINUTES_IN_YEAR = MINUTES_IN_DAY * DAYS_IN_YEAR
SECONDS_IN_MINUTE = 60
SECONDS_IN_HOUR = SECONDS_IN_MINUTE * MINUTES_IN_HOUR
SECONDS_IN_DAY = SECONDS_IN_HOUR * HOURS_IN_DAY
SECONDS_IN_YEAR = SECONDS_IN_DAY * DAYS_IN_YEAR
