"""RSGP constants."""

DAYS_IN_YEAR = 365
HOURS_IN_DAY = 24
HOURS_IN_YEAR = HOURS_IN_DAY * DAYS_IN_YEAR
MINUTES_IN_HOUR = 60
MINUTES_IN_DAY = MINUTES_IN_HOUR * HOURS_IN_DAY
MINUTES_IN_YEAR = MINUTES_IN_DAY * DAYS_IN_YEAR
SECONDS_IN_MINUTE = 60
SECONDS_IN_HOUR = SECONDS_IN_MINUTE * MINUTES_IN_HOUR
SECONDS_IN_DAY = SECONDS_IN_HOUR * HOURS_IN_DAY
SECONDS_IN_YEAR = SECONDS_IN_DAY * DAYS_IN_YEAR

BYTES_IN_KB = 1024
BYTES_IN_MB = BYTES_IN_KB * 1024
BYTES_IN_GB = BYTES_IN_MB * 1024
BYTES_IN_TB = BYTES_IN_GB * 1024

EPSILON = 0.0000001
