graph TB

  subgraph HHC[Hardware Houses Controls]
    HHC_H1([House 1])
    HHC_H2([House 2])
    HHC_H3([House 3])
  end

  subgraph RSGPS[RSG Prototype System]
    RSGPS_TLS[Time/Location Simulation]
    RSGPS_SSS[Solar System Simulation]
    RSGPS_HLS[Houses Loads Simulation]
    RSGPS_PM[Power Management]
    RSGPS_MA[Mobile API]
  end

  subgraph UMA[Users Mobile App]
    UMA_U1([User 1])
    UMA_U2([User 2])
    UMA_U3([User 3])
  end

  RSGPS_TLS <--Data--> RSGPS_SSS & RSGPS_HLS
  RSGPS_SSS & RSGPS_HLS <--Data--> RSGPS_PM <--Data--> RSGPS_MA
  HHC_H1 & HHC_H2 & HHC_H3 --Controls---> RSGPS_HLS
  RSGPS_MA <--Data & Controls--> UMA_U1 & UMA_U2 & UMA_U3
  