graph TB
  subgraph SS[Solar System]
    SS_P[Panels]
    SS_B[Batteries]
    SS_I[Inverter]
  end

  subgraph HHS[Hardware Houses Controls]
    HHS_H1[House 1]
    HHS_H2[House 2]
    HHS_H3[House 3]
  end

  subgraph RSG[RSG]
    RSG_PM([Power Management])
    RSG_HAA([Householder App APIs])
  end

  subgraph HMA[Householder Mobile App]
    HMA_H1([Householder 1])
    HMA_H2([Householder 2])
    HMA_H3([Householder 3])
  end

  SS_P --Power--> SS_I
  SS_B <--Power--> SS_I

  SS_I <--Data & Controls--> RSG_PM
  SS_I <--Load & Grid--> RSG_PM

  HHS_H1 & HHS_H2 & HHS_H3 <--Load & Grid--> RSG_PM

  RSG_PM <--Data--> RSG_HAA
  RSG_HAA <--Data & Controls--> HMA_H1 & HMA_H2 & HMA_H3
