graph TB
  subgraph SS[Solar System]
    SS_P([Panels])
    SS_B([Batteries])
    SS_I([Inverter])
  end

  subgraph RSGS[RSG System]
    RSGS_PM[Power Mng.]
    RSGS_MA[Mobile API]
  end

  subgraph HS[Houses]
    HS_H1([House 1])
    HS_H2([House 2])
    HS_H3([House 3])
  end

  subgraph UMA[Users Mobile App]
    UMA_U1([User 1 App])
    UMA_U2([User 2 App])
    UMA_U3([User 3 App])
  end

  SS_P --Power--> SS_I
  SS_B <--Power--> SS_I

  SS_I <--Data & Controls--> RSGS_PM
  SS_I <--Load & Grid--> RSGS_PM

  HS_H1 & HS_H2 & HS_H3 <--Load & Grid--> RSGS_PM

  RSGS_PM <--Data--> RSGS_MA
  RSGS_MA <--Data & Controls--> UMA_U1 & UMA_U2 & UMA_U3
