graph TB

  subgraph HHC[Hardware Houses Controls]
    HHC_H1[House 1]
    HHC_H2[House 2]
    HHC_H3[House 3]
  end

  subgraph RSGP[RSG Prototype]
    RSGP_TS([Time Simulation])
    RSGP_SSS([Solar System Simulation])
    RSGP_HLS([Houses Loads Simulation])
    RSGP_PM([Power Management])
    RSGP_HAA([Householder App APIs])
  end

  subgraph HMA[Householder Mobile App]
    HMA_H1([Householder 1])
    HMA_H2([Householder 2])
    HMA_H3([Householder 3])
  end

  AD([Admin Dashboard])

  HHC_H1 & HHC_H2 & HHC_H3 --Electric Signals--> RSGP
  AD <--Data & Controls--> RSGP
  RSGP_TS <--Data--> RSGP_SSS & RSGP_HLS <--Data--> RSGP_PM <--Data--> RSGP_HAA
  RSGP_HAA <--Data & Controls--> HMA_H1 & HMA_H2 & HMA_H3
