graph TD

  HS[Houses Simulator]
  HS --> HS_H1[House 1] --> HS_H1_D[Device Collection]
  HS --> HS_H2[House 2] --> HS_H2_D[Device Collection]
  HS --> HS_HK[...]
  HS --> HS_HN[House N] --> HS_HN_D[Device Collection]
  HS --> TLC[Total Load Calculation] --> PMI[Power Management Interface]
