graph TD

  HS[محاكاة المنازل]
  HS --> HS_H1[المنزل 1] --> HS_H1_D[مجموعة الجهاز]
  HS --> HS_H2[المنزل 2] --> HS_H2_D[مجموعة الجهاز]
  HS --> HS_HK[...]
  HS --> HS_HN[المنزل N] --> HS_HN_D[مجموعة الجهاز]
  HS --> TLC[حساب الحمل الكلي] --> PMI[واجهة إدارة الطاقة]
