graph TB

  subgraph HHC[Hardware Houses Controls]
    HHC_H1([House 1])
    HHC_H2([House 2])
    HHC_H3([House 3])
  end

  subgraph RSGP[RSGP]
    RSGP_SSS([Solar System Simulation])
    RSGP_PM([Power Management])
    RSGP_HS([Houses Simulation])
    RSGP_IOT([I/O Tracker])
    RSGP_RO([RSGP Remote Object])
  end

  subgraph D[Dashboard]
    D_V([Views])
    D_A([App])
  end

  RSGP_SSS <--Data--> RSGP_PM <--Data--> RSGP_HS
  RSGP_HS <--Data--> RSGP_IOT <--Electric Signals--> HHC_H1 & HHC_H2 & HHC_H3
  RSGP_RO <--Data--> D_A
