graph BT

  subgraph RSGP_HS[محاكاة المنازل]
    subgraph RSGP_HS_H1[المنزل 1]
      RSGP_HS_H1_D1([الجهاز 1])
      RSGP_HS_H1_D2([الجهاز 2])
      RSGP_HS_H1_DK([...])
      RSGP_HS_H1_DN([الجهاز N])
    end
    subgraph RSGP_HS_H2[المنزل 2]
      RSGP_HS_H2_D1([الجهاز 1])
      RSGP_HS_H2_D2([الجهاز 2])
      RSGP_HS_H2_DK([...])
      RSGP_HS_H2_DN([الجهاز N])
    end
    subgraph RSGP_HS_HK[...]
    end
    subgraph RSGP_HS_HN[المنزل N]
      RSGP_HS_H3_D1([الجهاز 1])
      RSGP_HS_H3_D2([الجهاز 2])
      RSGP_HS_H3_DK([...])
      RSGP_HS_H3_DN([الجهاز N])
    end
  end
