graph BT

  subgraph RSGP_HS[Houses Simulation]
    subgraph RSGP_HS_H1[House 1]
      RSGP_HS_H1_D1([Device 1])
      RSGP_HS_H1_D2([Device 2])
      RSGP_HS_H1_DK([...])
      RSGP_HS_H1_DN([Device N])
    end
    subgraph RSGP_HS_H2[House 2]
      RSGP_HS_H2_D1([Device 1])
      RSGP_HS_H2_D2([Device 2])
      RSGP_HS_H2_DK([...])
      RSGP_HS_H2_DN([Device N])
    end
    subgraph RSGP_HS_HK[...]
    end
    subgraph RSGP_HS_HN[House N]
      RSGP_HS_H3_D1([Device 1])
      RSGP_HS_H3_D2([Device 2])
      RSGP_HS_H3_DK([...])
      RSGP_HS_H3_DN([Device N])
    end
  end
